### ISSUE TITLE
update_user is hardcoded to PUT

### ISSUE THREAD

**Issue by sreestempus** [Shopify/oktakit#14]
https://github.com/Shopify/oktakit/blob/3ffb4efdc807df7f050fb4eacb7672fdd5edc59c/lib/oktakit/client/users.rb#L62-L64

whereas POST is needed for any partial update. 
https://developer.okta.com/docs/api/resources/users#update-user

Not sure how you want to handle multiple verbs per method. Am not experienced in idiomatic ruby. Would be happy to write the PR given an opinion of how that is normally done.

**Comment by jules2689** [comment]
This might help: https://github.com/Shopify/oktakit/pull/15

**Comment by jules2689** [comment]
#15 resolves this!
